# Generated by Django 4.2.7 on 2023-11-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='老师id')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='老师姓名')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='teachers',
        ),
        migrations.CreateModel(
            name='ReviewTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.review', verbose_name='评价id')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.teacher', verbose_name='老师id')),
            ],
            options={
                'db_table': 'review_teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.course', verbose_name='课程id')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.teacher', verbose_name='老师id')),
            ],
            options={
                'db_table': 'course_teacher',
            },
        ),
        migrations.AddConstraint(
            model_name='reviewteacher',
            constraint=models.UniqueConstraint(fields=('review_id', 'teacher_id'), name='primary_key4'),
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.UniqueConstraint(fields=('course_id', 'teacher_id'), name='primary_key5'),
        ),
    ]
