# Generated by Django 4.2.7 on 2023-11-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_teacher_remove_review_teachers_reviewteacher_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
