# Generated by Django 4.2.7 on 2023-11-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_teacher_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='课程评分'),
        ),
    ]
