# Generated by Django 4.2.7 on 2023-11-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='课程简介', max_length=2000, verbose_name='课程简介'),
        ),
    ]
