# Generated by Django 4.2.7 on 2023-11-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='review_id',
        ),
        migrations.CreateModel(
            name='NewCommentNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.notification')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.comment', verbose_name='新增评论')),
            ],
            options={
                'db_table': 'newcommentnotification',
            },
            bases=('judge.notification',),
        ),
        migrations.CreateModel(
            name='NewReviewNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.notification')),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.review', verbose_name='新增评价')),
            ],
            options={
                'db_table': 'newreviewnotification',
            },
            bases=('judge.notification',),
        ),
    ]
